### ISSUE TITLE
Missing data in Readme

### ISSUE THREAD

**Issue by Eugeniusz-Gienek** [synman/OctoPrint-MqttChamberTemperature#4] opened 2024-04-20 21:11 UTC
I have found out that there is a very important thing to make this plugin actually work which is missing from the description.
So, when one has this plugin installed and configured - nothing happens UNTIL you go to the OctoPrint settings, printer profiles and tick the "heated chamber" checkbox in the "print bed and build volume" tab of your printer profile. This is absolutely counterintuitive and got me frustrated until I finally had figured out that this does the trick.
What I recommend is put into the README the following information:

> In order to make this plugin work please go to the Octoprint printer profile settings, "print bed and build volume" tab and tick the "heated chamber" checkbox. Besides, please verify that the MQTT plugin is installed and properly configured.

Thanks :)

**Comment by synman** [comment] 2024-05-04 19:32
duplicate of details captured here:  https://github.com/synman/OctoPrint-MqttChamberTemperature/issues/1#issuecomment-1891006388

**Closed by synman** 2024-05-04 19:32 UTC
Labels: documentation
